language: node_js
node_js:
  - stable

before_script:
  - yarn bootstrap

script:
  - yarn test
  - |
    if [[ $TRAVIS_COMMIT_MESSAGE =~ ^docs ]] ; then
      yarn site:build
    fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: website/public
  on:
    branch: master
    condition: $TRAVIS_COMMIT_MESSAGE =~ ^docs
