language: node_js
node_js:
  - stable

before_script:
  - yarn bootstrap

script:
  - yarn test
  - yarn site:build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: website/public
  on:
    branch: master
    condition: $TRAVIS_COMMIT_MESSAGE =~ ^docs
